#!/bin/sh

if [ -z $1 ]; then
    gh pr view $(GH_PAGER= gh pr list -S 'review-requested:danielsuguimoto' | fzf --preview 'echo {} | awk "{print \$1}" | xargs gh pr view' | awk '{print $1}') --web
else
    gh pr view $1 --web
fi
