#!/bin/bash
# Usage: git create-mr target_branch

if [ -z $1 ]; then
    echo -e "\033[1;31m*** No target  branch name was given!  ***\033[0m"
    exit 1
fi

project=$(git remote -v | head -n1 | awk '{print $2}' | sed -e 's,.*:\(.*/\)\?,,' -e 's/\.git$//')
branch=$(git branch | grep \* | cut -d ' ' -f2)
user=$(curl -s 'https://gitlab.com/api/v4/users?private_token={PERSONAL_ACCESS_TOKEN}&search={USER_NAME}' | jq '.[0].id')
projectData=$(curl -s "https://gitlab.com/api/v4/users/$user/projects?private_token={PERSONAL_ACCESS_TOKEN}&search=$project")
sourceProjectId=$(jq '.[0].id' <<< "$projectData")
targetProjectId=$(jq '.[0].forked_from_project.id' <<< "$projectData")

xdg-open "https://gitlab.com/{USER_NAME}/$project/merge_requests/new?merge_request%5Bsource_branch%5D=$branch&merge_request%5Bsource_project_id%5D=$sourceProjectId&merge_request%5Btarget_branch%5D=$1&merge_request%5Btarget_project_id%5D=$targetProjectId"
