#!/bin/bash
# Usage: git create-project repository_url

if [ -z $1 ]; then
    echo -e "\033[1;31m*** No repository was given!  ***\033[0m"
    exit 1
fi

project=$(sed -e 's,.*:\(.*/\)\?,,' -e 's/\.git$//' <<< $1)
user=$(curl -s 'https://gitlab.com/api/v4/users?private_token={PERSONAL_ACCESS_TOKEN}&search={USER_NAME}' | jq '.[0].id')
projectData=$(curl -s "https://gitlab.com/api/v4/users/$user/projects?private_token={PERSONAL_ACCESS_TOKEN}&search=$project")
upstream=$(jq '.[0].forked_from_project.ssh_url_to_repo' <<< "$projectData")

echo $project
git clone $1
cd "$project"
git remote add upstream $upstream
