#!/bin/sh
# Usage: git create-branch branch_name source_branch

echo
if [ -z $1 ]; then
    echo -e "\033[1;31m*** No branch name was given!  ***\033[0m"
    exit 1
else
    target_branch=$1
fi

if [ -z $2 ]; then
    source_branch="."
else
    source_branch=$2
fi

git checkout $source_branch
git add --all
git stash
git pull
git checkout -b $target_branch
git push -u origin $target_branch
git stash pop
